# Generated by Django 5.2.17 on 2026-09-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='locations.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'created_at'], name='locview_location_created_idx')],
            },
        ),
    ]
