# Generated by Django 5.2.17 on 2026-09-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_locationview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
